### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by bkamantha** [ArjunKini/Fruit-Freshness-Detection#1]
_,cnts, h = cv2.findContours(edged.copy(), cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by SeemaManju** [comment]
Hello, i am having trouble with list index

IndexError                                Traceback (most recent call last)
<ipython-input-17-672eddb58fd1> in <module>
      1 _,cnts, h = cv2.findContours(edged.copy(), cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
      2 
----> 3 max_contA=cv2.contourArea(cnts[0])
      4 max_cont=max(cnts,key=cv2.contourArea)
      5 

IndexError: list index out of range

and also i am new to this could you please tell me how to include the image to the file
